CLUSTERMAN-637: Add basic Rookout support
YelpArchive/clusterman pull request #159
Opened 2022-06-02 13:39 UTC by BeryJu

### Description

COMPINFRA-1009, adding it to clusterman first as there's a bunch of tooling and setup already done that makes it easier to add rookout to paasta services, compared to other projects

Rookout is disabled by default so this should be safe to deploy, can be enabled at any time from soaconfigs

2022-06-02 15:41 UTC, nemacysts approved these changes
do we need to do anything to enable rookout for our custom signals? or will they automatically be instrumented by this?

2022-06-02 15:41 UTC, nemacysts commented on requirements-minimal.txt
> +psutil==5.9.1
```suggestion
rook
```

this file should only include libraries that are directly imported in production code

2022-06-02 15:41 UTC, nemacysts requested changes
err, misclicked

2022-06-02 15:45 UTC, BeryJu commented
> do we need to do anything to enable rookout for our custom signals? or will they automatically be instrumented by this?

Good question, since they are completely independent sub-processes (afaik that's the case), we'll have to import the SDK there too. Also, I can't remember if the signals are continuously running, or if they are started, do their thing and then exit, because if the latter is the case then rookout doesn't work that well with that yet

2022-06-03 15:07 UTC, nemacysts approved these changes

2022-06-03 15:07 UTC, nemacysts commented on clusterman/tools/rookout.py
> +def enable_rookout():
```suggestion
def enable_rookout() -> None:
```

dunno how i missed that in the original review :p

2022-06-03 15:10 UTC, BeryJu commented on clusterman/tools/rookout.py
> +def enable_rookout():
do'h me neither

2022-06-03 16:27 UTC, nemacysts approved these changes

2022-06-07 13:33 UTC, BeryJu commented
I'm a bit confused why all the tests succeed since both of the clusterman imports were incorrect (`from clusterman.clusterman.tools.rookout import enable_rookout` instead of `from clusterman.tools.rookout import enable_rookout`)

2022-06-07 15:11 UTC, merged