Correct Yelp developer instructions
YelpArchive/clusterman pull request #65
Opened 2020-10-08 11:11 UTC by JoeMalt

`git add remote` should be `git remote add`

### Description

Please fill out!

### Testing Done

Please fill out!  Generally speaking any new features should include
additional unit or integration tests to ensure the behaviour is
working correctly.

2020-10-14 20:50 UTC, drmorr0 requested changes

2020-10-14 20:50 UTC, drmorr0 commented on README.md
>  3) In your local repository run
While we're here, please delete step 3).  This is no longer necessary.

2020-10-15 15:45 UTC, drmorr0 approved these changes

2020-10-15 15:45 UTC, drmorr0 commented
Thanks for doing this!  up-to-date documentation++

2020-10-15 15:49 UTC, JoeMalt commented
Merged into master. I branched off the wrong branch so GH doesn't think this is merged, but it is

2020-10-15 15:49 UTC, closed without merging